### ISSUE TITLE
Add README files for all algorithms and problems

### ISSUE THREAD

**Issue by kartikcode** [kartikcode/Data-Structures-Algorithms#15]
Add a general README.md file to all the folders containing any special algorithm or problem.<br/> The README file should contain a bit specification about the algorithm/problem and some possible helpful links for further reseach on the topic.

**Comment by ap-jain** [comment]
i can do this

**Comment by kartikcode** [comment]
Yes, sure!

**Comment by kartikcode** [comment]
Resolved
